wings/quizblock/urls.py
from django.conf.urls import url
from .views import (
    edit_quiz, add_question_to_quiz, edit_question, add_answer_to_question,
    delete_question, reorder_answers, reorder_questions,
    delete_answer, edit_answer,
)

urlpatterns = [
    url(r'^edit_quiz/(?P<id>\d+)/$', edit_quiz, {}, 'edit-quiz'),
    url(r'^edit_quiz/(?P<id>\d+)/add_question/$', add_question_to_quiz, {},
        'add-question-to-quiz'),
    url(r'^edit_question/(?P<id>\d+)/$', edit_question, {}, 'edit-question'),
    url(r'^edit_question/(?P<id>\d+)/add_answer/$', add_answer_to_question,
        {}, 'add-answer-to-question'),
    url(r'^delete_question/(?P<id>\d+)/$', delete_question, {},
        'delete-question'),
    url(r'^reorder_answers/(?P<id>\d+)/$', reorder_answers, {},
        'reorder-answer'),
    url(r'^reorder_questions/(?P<id>\d+)/$', reorder_questions, {},
        'reorder-questions'),
    url(r'^delete_answer/(?P<id>\d+)/$', delete_answer, {}, 'delete-answer'),
    url(r'^edit_answer/(?P<id>\d+)/$', edit_answer, {}, 'edit-answer'),
]

wings/urls.py
import django.views.static

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from wings.wings_main.views import (
    background, first, all_answers, text_answers, all_answers_key,
    all_answers_key_table, timestamps, summary, launch_participant,
    exit_materials, participant_exit_materials
)
from wings.analytics.views import log_action
from pagetree.views import move_section
from wings.main.views import page, edit_page

admin.autodiscover()

urlpatterns = [
    url('^$', RedirectView.as_view(url='/admin/wings_main/participant/')),
    url('^accounts/login/$',
        RedirectView.as_view(url='/admin/wings_main/participant/')),
    url('^login/$',
        RedirectView.as_view(url='/admin/wings_main/participant/')),
    url('^accounts/profile/$',
        RedirectView.as_view(url='/admin/wings_main/participant/')),


    url('^about/$', background, {'content_to_show': 'about'}),
    url('^help/$', background, {'content_to_show': 'help'}),
    url('^contact/$', background, {'content_to_show': 'contact'}),
    url('^credits/$', background, {'content_to_show': 'credits'}),
    url('^logout/$', RedirectView.as_view(url='/admin/logout/')),

    # shortcut to first page of the
    url('^first/$', first),

    # giant table of all answers from all participants
    url('^all_answers/$', all_answers),
    url('^text_answers/$', text_answers),
    url('^all_answers_key/$', all_answers_key),
    url('^all_answers_key_table/$', all_answers_key_table),
    url('^timestamps/$', timestamps),

    # summary of all pages
    url('^summary/$', summary),

    # start the participant off:
    url(r'^participant/(?P<id_string>\d+)/launch/', launch_participant),

    # exit materials for a particular participant (meant to be accessed by the
    # facilitator from the list of participants)
    url(r'^participant/(?P<id_string>\d+)/exit_materials/', exit_materials),

    # exit materials for the logged in user:
    url(r'^exit_materials/', participant_exit_materials),

    url(r'^pagetree/', include('pagetree.urls')),
    url(r'^_quiz/', include('wings.quizblock.urls')),

    # Logging clicks on UI elements via AJAX:
    url(r'^log_action/(?P<action_id>\d+)/on_section/(?P<section_id>\d+)/$',
        log_action),

    # standard django stuff:
    url('^accounts/', include('djangowind.urls')),
    url(r'^admin/pagetree/section/move/(?P<section_id>\d+)/$', move_section,
        {}, 'move-section'),

    url(r'^admin/', include(admin.site.urls)),

    url('^smoketest/', include('smoketest.urls')),

    url(r'^uploads/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.UPLOADS_ROOT}),

    # from forest:
    # Put this after the static files, otherwise it will try
    # to serve them.
    url(r'^edit/(?P<path>.*)$', edit_page, {}, 'edit-page'),
    url(r'^(?P<path>.*)$', page),
]

wings/main/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import hashlib
from django.apps import apps
from django.conf import settings
from pagetree.helpers import get_section_from_path


class Stand(models.Model):
    title = models.CharField(
        max_length=256,
        default=u"",
        blank=True,
        null=True)
    hostname = models.CharField(max_length=256, db_index=True)
    created = models.DateTimeField(auto_now=True)
    css = models.TextField(default=u"", blank=True, null=True)
    description = models.TextField(default=u"", blank=True, null=True)

    access = models.CharField(
        max_length=256, default="open",
        choices=(('open', 'Open Access'),
                 ('login', 'Logged-in Users Only'),
                 ('group',
                  'Users in Selected Group(s) Only'),
                 ('whitelist', 'Whitelisted Users Only')))

    def __unicode__(self):
        return self.title

    def get_root(self):
        """ return the Root pagetree.Section for this Stand """
        section = get_section_from_path("/", hierarchy=self.hostname)
        return section.hierarchy.get_root()

    def css_hash(self):
        sha1 = hashlib.sha1()
        sha1.update(self.css)
        return sha1.hexdigest()

    def can_edit(self, user):
        if not user:
            return False
        if user.is_anonymous():
            return False
        if user.is_superuser:
            return True
        r = StandUser.objects.filter(stand=self, user=user)
        if r.count() > 0:
            su = r[0]
            if su.access in ["admin", "faculty", "ta"]:
                return True
        if self.user_in_allowed_edit_group(user):
            return True
        return False

    def can_view(self, user):
        if not user:
            return False
        if self.access == "open":
            return True
        if user.is_anonymous():
            return False
        if user.is_superuser:
            return True
        r = StandUser.objects.filter(stand=self, user=user)
        if r.count() > 0:
            return True
        if self.user_in_allowed_group(user):
            return True
        return False

    def can_admin(self, user):
        if not user:
            return False
        if user.is_anonymous():
            return False
        if user.is_superuser:
            return True
        r = StandUser.objects.filter(stand=self, user=user)
        if r.count() > 0:
            su = r[0]
            if su.access == "admin":
                return True
        if self.user_in_allowed_admin_group(user):
            return True
        return False

    def user_in_allowed_group(self, user):
        allowed_groups = []
        for g in StandGroup.objects.filter(stand=self):
            allowed_groups.append(g.group.name)
        for g in user.groups.all():
            if g.name in allowed_groups:
                # bail as soon as we find a group affil that's allowed
                return True
        return False

    def user_in_allowed_edit_group(self, user):
        allowed_groups = []
        for g in StandGroup.objects.filter(stand=self):
            if g.access in ["admin", "faculty", "ta"]:
                allowed_groups.append(g.group.name)
        for g in user.groups.all():
            if g.name in allowed_groups:
                # bail as soon as we find a group affil that's allowed
                return True
        return False

    def user_in_allowed_admin_group(self, user):
        allowed_groups = []
        for g in StandGroup.objects.filter(stand=self):
            if g.access == "admin":
                allowed_groups.append(g.group.name)
        for g in user.groups.all():
            if g.name in allowed_groups:
                # bail as soon as we find a group affil that's allowed
                return True
        return False

    def available_pageblocks(self):
        enabled = [pb.block for pb in self.standavailablepageblock_set.all()]
        return (
            [apps.get_model(*pb.split('.'))
             for pb in settings.PAGEBLOCKS if pb in enabled]
        )


class StandUser(models.Model):
    stand = models.ForeignKey(Stand)
    user = models.ForeignKey(User)
    access = models.CharField(max_length=16, default="student")

    class Meta:
        ordering = ('user__last_name', 'user__first_name')


class StandGroup(models.Model):
    stand = models.ForeignKey(Stand)
    group = models.ForeignKey(Group)
    access = models.CharField(max_length=16, default="student")


class StandSetting(models.Model):
    stand = models.ForeignKey(Stand)
    name = models.CharField(max_length=256, db_index=True)
    value = models.CharField(max_length=256)


class StandAvailablePageBlock(models.Model):
    stand = models.ForeignKey(Stand)
    block = models.CharField(max_length=256, db_index=True)


def get_stand(hostname, user=None):
    r = Stand.objects.filter(hostname=hostname)
    if r.count() > 0:
        return r[0]
    return None

wings/main/forms.py
from models import Stand
from django.forms import ModelForm


class StandForm(ModelForm):

    class Meta:
        model = Stand

wings/wings_main/forms.py
from models import Video, Series
from django import forms


class AddSeriesForm(forms.ModelForm):

    class Meta:
        model = Series


class UploadVideoForm(forms.ModelForm):

    class Meta:
        model = Video

wings/analytics/views.py
from django.http import HttpResponse
from .models import ActionTaken, ActionType
from pagetree.models import Section


def log_action(request, action_id, section_id):
    the_section = Section.objects.get(pk=section_id)
    the_action = ActionType.objects.get(pk=action_id)
    ActionTaken.log(the_action, the_section, request.user)
    return HttpResponse('{}', content_type='application/json')

wings/main/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from pagetree.helpers import get_section_from_path, get_module
from pagetree.helpers import needs_submit, submitted
from django.contrib.auth.decorators import login_required

from .models import get_stand

from wings.analytics.models import ActionType

from wings.wings_main.views import decoration_info, whether_to_show_decorations
from wings.wings_main.views import check_next_page
from wings.wings_main.views import destination_on_check_next_page_fail


class stand(object):

    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, func):
        def stand_func(request, *args, **kwargs):
            stand = get_stand(request.get_host())
            if not stand:
                return HttpResponse("no such site")
            request.stand = stand
            items = func(request, *args, **kwargs)
            if isinstance(items, type({})):
                items['stand'] = stand
            return items
        return stand_func


def root_page(section, root):
    # trying to visit the root page
    if section.get_next():
        # just send them to the first child
        return HttpResponseRedirect(section.get_next().get_absolute_url())
    else:
        # send them to the stand admin interface
        return HttpResponseRedirect("/_stand/")


@login_required
@stand()
def page(request, path):
    hierarchy = request.get_host()
    section = get_section_from_path(path, hierarchy=hierarchy)
    root = section.hierarchy.get_root()
    module = get_module(section)

    if not request.stand.can_view(request.user):
        return HttpResponse("you do not have permission")
    if section.id == root.id:
        return root_page(section, root)

    if request.method == "POST":
        # user has submitted a form. deal with it
        section.submit(request.POST, request.user)
        next_path = path_from_destination(request, section)
        if next_path is not None:
            return HttpResponseRedirect(next_path)
    # Wings-specific modifications:
    if not check_next_page(request, section):
        return (
            HttpResponseRedirect(
                destination_on_check_next_page_fail(request))
        )
    show_decorations = whether_to_show_decorations(section)
    the_decoration_info = decoration_info(section)
    action_type_summary = ActionType.summary()

    return render(
        request, 'main/page.html',
        dict(
            section=section,
            module=module,
            needs_submit=needs_submit(section),
            is_submitted=submitted(section, request.user),
            stand=request.stand,
            modules=root.get_children(),
            root=section.hierarchy.get_root(),
            can_edit=request.stand.can_edit(request.user),
            can_admin=request.stand.can_admin(request.user),
            show_decorations=show_decorations,
            decoration_info=the_decoration_info,
            action_type_summary=action_type_summary
        ))


def path_from_destination(request, section):
    if request.POST['destination'] == '':
        return section.get_absolute_url()

    if request.POST['destination'] == 'previous':
        return section.get_previous().get_absolute_url()

    if request.POST['destination'] == 'next':
        return section.get_next().get_absolute_url()


@login_required
@stand()
def edit_page(request, path):
    hierarchy = request.get_host()
    section = get_section_from_path(path, hierarchy=hierarchy)
    if not request.stand.can_edit(request.user):
        return HttpResponse("you do not have admin permission")
    can_admin = request.stand.can_admin(request.user)
    root = section.hierarchy.get_root()
    return render(
        request, 'main/edit_page.html',
        dict(section=section,
             module=get_module(section),
             modules=root.get_children(),
             stand=request.stand,
             can_admin=can_admin,
             available_pageblocks=request.stand.available_pageblocks(),
             root=section.hierarchy.get_root()))

wings/quizblock/views.py
from .models import Quiz, Question, Answer
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse


def edit_quiz(request, id):
    quiz = get_object_or_404(Quiz, id=id)
    section = quiz.pageblock().section
    return render(request, 'quizblock/edit_quiz.html',
                  dict(quiz=quiz, section=section))


def delete_question(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        quiz = question.quiz
        question.delete()
        return HttpResponseRedirect(reverse("edit-quiz", args=[quiz.id]))
    return HttpResponse("""
<html><body><form action="." method="post">Are you Sure?
<input type="submit" value="Yes, delete it" /></form></body></html>
""")


def delete_answer(request, id):
    answer = get_object_or_404(Answer, id=id)
    if request.method == "POST":
        question = answer.question
        answer.delete()
        return (
            HttpResponseRedirect(reverse("edit-question", args=[question.id]))
        )
    return HttpResponse("""
<html><body><form action="." method="post">Are you Sure?
<input type="submit" value="Yes, delete it" /></form></body></html>
""")


def reorder_answers(request, id):
    if request.method != "POST":
        return HttpResponse("only use POST for this")
    question = get_object_or_404(Question, id=id)
    keys = sorted(request.GET.keys())
    answers = [int(request.GET[k]) for k in keys if k.startswith('answer_')]
    question.update_answers_order(answers)
    return HttpResponse("ok")


def reorder_questions(request, id):
    if request.method != "POST":
        return HttpResponse("only use POST for this", status=400)
    quiz = get_object_or_404(Quiz, id=id)
    keys = request.GET.keys()
    question_keys = sorted([int(k[len('question_'):])
                           for k in keys if k.startswith('question_')])
    questions = [int(request.GET['question_' + str(k)]) for k in question_keys]
    quiz.update_questions_order(questions)
    return HttpResponse("ok")


def add_question_to_quiz(request, id):
    quiz = get_object_or_404(Quiz, id=id)
    form = quiz.add_question_form(request.POST)
    if form.is_valid():
        question = form.save(commit=False)
        question.quiz = quiz
        question.save()
    return HttpResponseRedirect(reverse("edit-quiz", args=[quiz.id]))


def edit_question(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        form = question.edit_form(request.POST)
        question = form.save(commit=False)
        question.save()
        return (
            HttpResponseRedirect(reverse("edit-question", args=[question.id]))
        )
    return render(request, 'quizblock/edit_question.html',
                  dict(question=question))


def add_answer_to_question(request, id):
    question = get_object_or_404(Question, id=id)
    form = question.add_answer_form(request.POST)
    if form.is_valid():
        answer = form.save(commit=False)
        answer.question = question
        if answer.label == '':
            answer.label = answer.value
        answer.save()
    return HttpResponseRedirect(reverse("edit-question", args=[question.id]))


def edit_answer(request, id):
    answer = get_object_or_404(Answer, id=id)
    if request.method == "POST":
        form = answer.edit_form(request.POST)
        answer = form.save(commit=False)
        answer.save()
        return HttpResponseRedirect(reverse("edit-answer", args=[answer.id]))
    return render(request, 'quizblock/edit_answer.html', dict(answer=answer))

wings/templates/main/add_stand.html
{% extends 'base.html' %}
{% block title %}Add Stand{% endblock %}
{% block content %}
{% if created %}
<p>Your new stand has been created, but may not be accessible yet. 
  You can either wait for the DNS registration to complete, or you can modify your /etc/hosts and
  then click <a href="//{{stand.hostname}}/_stand/">here</a> to begin configuring and adding content.</p>
<p>See <a href="http://support.apple.com/kb/TA27291">Apple's
    instructions for doing this on OS X</a> [insert Windows
    instructions here?]</p>
{% else %}
<h2>Create a new Stand</h2>
<form action="." method="post">
<table>
{{form.as_table}}
</table>
<input type="submit" value="add" />
</form>
{% endif %}
{% endblock %}

wings/templates/main/clone.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
  <p>
    Clone to what hostname?
    <input type="text" name="new_hierarchy" />
  </p>
  <p>
    Copy user permissions?
    <input type="checkbox" name="copy_userperms" />
  </p>
  <input type="submit" value="Clone it!" />
</form>
{% endblock %}

wings/templates/main/edit_page.html
{% extends "base.html" %}
{% block title %}{{section.label}} (edit){% endblock %}
{% block js %}
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.3/themes/base/jquery-ui.css" type="text/css" media="all" /> 
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
        type="text/javascript" ></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.3/jquery-ui.min.js" type="text/javascript"></script>

<script type="text/javascript">
var saveOrderOfChildren = function() {
    var url = "{% url 'reorder-section-children' section.id %}?";
    var worktodo = 0;
    jQuery("#children-order-list li").each(function(index,element) {
       worktodo = 1;
       var id = jQuery(element).attr('id').split("-")[1];
       url += "section_id_" + index + "=" + id + ";";
    });
    if (worktodo == 1) {
        var req = new XMLHttpRequest();
        req.open("POST",url,true);
        req.send(null);
    }
};

var saveOrderOfPageBlocks = function() {
    var url = "{% url 'reorder-pageblocks' section.id %}?";
    var worktodo = 0;
    jQuery("#edit-blocks-tab div").each(function(index,element) {
      worktodo = 1;
      var id = jQuery(element).attr('id').split("-")[1];
      url += "pageblock_id_" + index + "=" + id + ";";
    });
    if (worktodo == 1) {
        /* only bother submitting if there are elements to be sorted */
        var req = new XMLHttpRequest();
        req.open("POST",url,true);
        req.send(null);
    }

}

</script>

<style type="text/css">
	#edit-blocks-tab .draggable { background-color: #ddd; }
	.draghandle {float: left;}
	#children-order-list {list-style-type: none; margin: 0; padding: 0;}
	#children li { margin: 0 3px 3px 3px; padding: 0.4em;
	padding-left: 1.5em; 
          background-color: #ddd;
	}
	#children li span { position: absolute; margin-left: -1.3em; }
	.dragging {border: #f60 solid 1px;}
	</style>
{% endblock %}

{% block primarynavtabs %}

<ul class="globalnav">
  {% for section in modules %}
  <li{% ifequal section.id module.id %} class="active"{% endifequal %}><a href="/edit{{section.get_absolute_url}}">{{section.label}}</a></li>
  {% endfor %}
</ul>

{% endblock %}


{% block sidenav %}
	<!-- ###### Secondary Navigation ###### -->
	<div id="secondary_navigation">
		<div id="fadetop"></div>
		<div class="block">
			<h3>Sections</h3>
{% with "/edit" as menu_base %}
{% include "main/menu.html" %}
{% endwith %}
		</div><!-- div id="block" -->
		<div id="fadebottom"></div>
	</div><!-- div id="secondary_navigation" -->
{% endblock %}


{% block content %}
<a href="{{section.get_absolute_url}}">view page</a>
<h1>{{ section.label }}</h1>

<div id="tabber">

<ul>
{% if section.pageblock_set.count %}
  <li><a href="#edit-blocks-tab">Edit Blocks</a></li>
{% endif %}
  <li><a href="#children-tab">Children</a></li>
  <li><a href="#add-pageblock-tab">Add Pageblock</a></li>
  <li><a href="#edit-page-tab">Edit Section</a></li>
</ul>

{% if section.pageblock_set.count %}
<div id="edit-blocks-tab"/>
{% for block in section.pageblock_set.all %}
<div class="block-edit draggable" id="pageblock-{{block.id}}">
<table width="100%" border="0"><tr><td><span title="drag to reorder pageblocks" class="draghandle ui-icon ui-icon-arrowthick-2-n-s"></span></td>
<td align="right">
<form action="{% url 'delete-pageblock' block.id %}" method="post">
<input type="submit" value="delete block {{block.ordinality}}" />
</form></td></tr>
<tr>
<td>
{% if block.block.exportable %}
<a href="{% url 'export-pageblock-json' block.id %}">export json</a>
{% endif %}
</td>
<td>
{% if block.block.importable %}
<a href="{% url 'import-pageblock-json' block.id %}">import json</a>
{% endif %}
</td>
</tr>
</table>
<form action="{% url 'edit-pageblock' block.id %}" method="post"
{% if block.edit_form.is_multipart %}enctype="multipart/form-data"{% endif %}>
<table width="100%">
{{ block.default_edit_form.as_table }}
{% with block.edit_form as ef %}
{{ ef.as_table }}
{% if ef.alt_text %}
<tr><td colspan="2">
{{ ef.alt_text|safe }}
</td></tr>
{% endif %}
{% endwith %}
</table>
<input type="submit" value="save" />
</form>
</div>
{% endfor %}
</div>
{% endif %}
<div id="children-tab">
<ul id="children-order-list">
{% for child in section.get_children %}
<li class="draggable"
    id="child-{{child.id}}"><span title="drag to reorder pageblocks" class="draghandle ui-icon ui-icon-arrowthick-2-n-s"></span>[<a href="/pagetree/delete_section/{{child.id}}/">delete</a>]
  {{child.label}}
</li>
{% endfor %}
</ul>

<form action="{% url 'add-child-section' section.id %}" method="post">
<table>
{{ section.add_child_section_form.as_table }}
</table>
<input type="submit" value="add child section" />
</form>
</div>


<div id="add-pageblock-tab">

{% for blocktype in available_pageblocks %}
{% if blocktype %}
<form action="{% url 'add-pageblock' section.id %}"
{% if blocktype.add_form.is_multipart %}
enctype="multipart/form-data"
{% endif %}
method="post">
<fieldset>
  <legend>add {{ blocktype.display_name }}</legend>
<input type="hidden" name="blocktype" value="{{blocktype.display_name}}"/>
<table width="100%">
{{section.add_pageblock_form.as_table}}
{{blocktype.add_form.as_table}}
</table>
<input type="submit" value="add {{blocktype.display_name}}" />
</fieldset>
</form>
{% endif %}
{% endfor %}
</div>

<div id="edit-page-tab">
<form action="{% url 'delete-section' section.id %}" method="post">
<input type="submit" value="delete this page" />
</form>

<form action="{% url 'edit-section' section.id %}" method="post">
<fieldset><legend>Edit Page</legend>
<table>
{{ section.edit_form.as_table }}
</table>
<input type="submit" value="save" />
</fieldset>
</form>
</div>

</div>

{% endblock %}

{% block content-nav %}

{% if section.get_previous %}
<a href="{% url 'edit-page' section.get_previous.get_path %}" id="previous">« {{section.get_previous.label}}</a>
{% endif %}

{% if section.get_next %}
<a href="{% url 'edit-page' section.get_next.get_path %}" id="next">{{section.get_next.label}} »</a>
{% endif %}

<script type="text/javascript">
jQuery(function() {
  jQuery("#children-order-list").sortable({
    containment : 'parent'
    ,axis : 'y'
    ,tolerance: 'pointer'
    ,activeClass: 'dragging'
    ,handle: '.draghandle'
    ,stop: function (event,ui) { saveOrderOfChildren();}
  });
  jQuery("#children-order-list").disableSelection();
  jQuery("#edit-blocks-tab").sortable({
    items : 'div'
    ,axis: 'y'
    ,containment: 'parent'
    ,handle: '.draghandle'
    ,activeClass: 'dragging'
    ,tolerance: 'pointer'
    ,stop: function (event,ui) { saveOrderOfPageBlocks();}
  });
  jQuery("#tabber").tabs();

  jQuery("#edit-blocks-tab").disableSelect();
});
</script>

{% endblock %}

wings/templates/main/import.html
{% extends "base.html" %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
  <input type="file" name="file" />
  <input type="submit" value="Import from ZIP" />
</form>
{% endblock %}

wings/templates/main/manage_blocks.html
{% extends 'base.html' %}
{% block title %}Manage Blocks{% endblock %}
{% block content %}
<form action="." method="post">

<table>
{% for block in all_blocks %}
<tr><td><input type="checkbox" name="{{block.name}}"
{% if block.enabled %}
checked="checked"
{% endif %} /></td><td>{{block.name}}</td></tr>
{% endfor %}
</table>

<input type="submit" value="save" />
</form>

<a href="/">Visit site</a>

{% endblock %}

wings/templates/main/menu.html
<ul>
{% for s in module.get_descendants %}
{% ifequal s.id module.id %}
{% else %}
<li class="menu-{{s.depth}}">
  {% ifnotequal s.id section.id %}
  <a href="{{menu_base}}{{s.get_absolute_url}}">
  {% else %}
     <b>
  {% endifnotequal %}
  {{s.label}}
  {% ifnotequal s.id section.id %}
    </a>
  {% else %}
    </b>
  {% endifnotequal %}

  {% if s.get_children %}
     <ul class="hs-init-hide" id="section-ul-{{s.id}}">
       {% else %}
  {% if s.is_last_child %}
     {% for lc in s.closing_children %}
     </ul>
     {% endfor %}
{% endif %}

{% endif %}

</li>

{% endifequal %}

{% endfor %}
</ul>

wings/templates/main/stand_groups.html
{% extends 'base.html' %}
{% block title %}Groups{% endblock %}
{% block content %}
<form action="add/" method="post">
<fieldset><legend>add group</legend>
<table>
<tr>
<td>
<b>Select existing group</b><br />
<select name="group">
<option value="" selected="selected">Select existing group</option>
{% for g in all_groups %}
<option value="{{g.id}}">{{g.name}}</option>
{% endfor %}
</select></td>
<td>
<b>access level</b><br />
<select name="access">
<option value="student">student</option>
<option value="instructor">instructor</option>
<option value="admin">admin</option>
</select></td>
<td>
<input type="submit" value="add" />
</td></tr>
</table>
</fieldset>
</form>


<table>
{% for standgroup in stand.standgroup_set.all %}
<tr class="{% cycle 'even' 'odd' %}">
<th>
<a href="{{standgroup.id}}/">{{standgroup.group.name}}</a>
</th>
<td>{{standgroup.access}}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

wings/templates/main/stand_users.html
{% extends 'base.html' %}
{% block title %}Users{% endblock %}
{% block content %}
<form action="add/" method="post">
<fieldset><legend>add user</legend>
<table>
<tr>
<td>
<b>Select existing user</b><br />
<select name="user">
<option value="" selected="selected">Select existing user</option>
<option value="">or Add by UNI</option>
{% for u in all_users %}
<option value="{{u.username}}">{{u.last_name}}, {{u.first_name}} ({{u.username}})</option>
{% endfor %}
</select></td>
<td>
<b>or enter UNI</b><br />
<input type="text" size="5" name="uni" />
<td>
<b>access level</b><br />
<select name="access">
<option value="student">student</option>
<option value="instructor">instructor</option>
<option value="admin">admin</option>
</select></td>
<td>
<input type="submit" value="add" />
</td></tr>
</table>
</fieldset>
</form>


<table>
{% for standuser in stand.standuser_set.all %}
<tr class="{% cycle 'even' 'odd' %}">
<th>
<a href="{{standuser.id}}/">{% if standuser.user.first_name %}
{{standuser.user.last_name}}, {{standuser.user.first_name}} 
({{standuser.user.username}})
{% else %}
{{standuser.user.username}}
{% endif %}</a>
</th>
<td>{{standuser.access}}</td>
</tr>
{% endfor %}
</table>
{% endblock %}